version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: contacthub
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: contacthub_test
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  postgres_test_data:
